version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - /home/runner/work/pruebas_curso/.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
